### ISSUE TITLE
Question about toDo

### ISSUE THREAD

**Issue by dernster** [jonfinerty/Once#31]
Reviewing the `public static void toDo(@Scope int scope, String tag)` function specification it says "if it has already marked to do or been done within that scope then it will not be marked." but the actual implementation does not involve the `THIS_APP_SESSION` scope. I'm wondering why the implementation does not check if the tag was done within that scope? Maybe we should have a session start timestamp in order to do that... what do you think?

**Comment by jonfinerty** [comment]
Well spotted, looks like a bug.

That should probably check the `sessionList` if the `THIS_APP_SESSION` scope is provided and only add the tag if it doesn't exist in the list.

longer term, I'd like to change how the sessionList works and shift to how you described, so you have a session timestamp and it mirrors how the version scope check works.

Other work here is that `toDo` doesn't work with timestamps yet, which would make it nice and symmetric with `beenDone`

**Comment by jonfinerty** [comment]
@dernster I've just checked the code, we have a test around this. It's not obvious from the code (because as you've seen the implementation doesn't explicitly check `THIS_APP_SESSION`), but actually because we only mark a tag as todo if its either it's never been done before, or if the scope is VERSION and we last saw the tag before the last update.

As I said this could use a refactor :) but it should be functional (check here: https://github.com/jonfinerty/Once/blob/master/once/src/test/java/jonathanfinerty/once/ToDoTests.java#L59 for validation)

**Comment by jonfinerty** [comment]
@dernster I'll going to close this, if that's ok? I'll do the refactoring at some point, but outside of this issue as it's more an enhancement.

**Comment by dernster** [comment]
@jonfinerty You are right! Thanks for clarifying that :)
It's ok to close this.

I was reviewing your code since I was thinking about implementing this library for Swift. Our Android team use this Once component a lot and for iOS there was nothing like this.
Finally did it! You can check out [Ecno](https://github.com/xmartlabs/Ecno) (Once in reverse :)). In the README file we have a reference to your library so I hope it's all fine.

Thanks!

**Comment by jonfinerty** [comment]
Amazing, thanks for the link, it's really cool someone is building upon something I built.
