### ISSUE TITLE
VERSION vs INSTALL tags backwards?

### ISSUE THREAD

**Issue by ryust** [jonfinerty/Once#52]
Maybe my understanding is wrong, but it seems THIS_APP_VERSION and THIS_APP_INSTALL are backwards. The VERSION tag is using package lastUpdateTime... shouldn't it be using package versionCode? Install is date oriented, while version is build number instead.

**Comment by jonfinerty** [comment]
I believe it should work how it is (but maybe my understanding is also wrong). 

`THIS_APP_INSTALL` just checks for any presence of the tag - so since the app was installed and Once started tracking the tag, no need to check the timestamps against anything.

I think the reason I chose to use `lastUpdateTime` (it's been a few years...) is that I can easily compare that datetime against the datetime when the tag was last seen, [lastUpdate time covers app updates](https://developer.android.com/reference/android/content/pm/PackageInfo#lastUpdateTime) so if a tag's timestamp is greater than that, you know it's been done since the last app version (which might be the same as install). `versionCode` would also work, but I'd need to store which versionCode the tags were mark done against, in addition to the timestamp (as that's needed for the 'in the last 5 min' functionality).
